/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import tp7.Materia;

/**
 *
 * @author carlo
 */
public class FormMaterias extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form FormMaterias
     */
    public FormMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloMat = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblAnioMat = new javax.swing.JLabel();
        lblNombreMat = new javax.swing.JLabel();
        txtCodigoMat = new javax.swing.JTextField();
        txtNombreMat = new javax.swing.JTextField();
        txtAnioMat = new javax.swing.JTextField();
        btnAceptarMat = new javax.swing.JButton();
        btnSalirMat = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(450, 290));

        lblTituloMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloMat.setText("Formulario Materias");

        lblCodigo.setText("Código");

        lblAnioMat.setText("Año de curso");

        lblNombreMat.setText("Nombre");

        btnAceptarMat.setText("Aceptar");
        btnAceptarMat.setPreferredSize(new java.awt.Dimension(90, 30));
        btnAceptarMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarMatActionPerformed(evt);
            }
        });

        btnSalirMat.setText("Salir");
        btnSalirMat.setPreferredSize(new java.awt.Dimension(90, 30));
        btnSalirMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirMatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(lblTituloMat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo)
                            .addComponent(lblNombreMat)
                            .addComponent(lblAnioMat))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoMat)
                            .addComponent(txtNombreMat)
                            .addComponent(txtAnioMat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnAceptarMat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(btnSalirMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMat)
                    .addComponent(txtNombreMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioMat)
                    .addComponent(txtAnioMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalirMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirMatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirMatActionPerformed

    private void btnAceptarMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarMatActionPerformed
        // TODO add your handling code here:
        if (!txtCodigoMat.getText().isEmpty() && !txtNombreMat.getText().isEmpty() && !txtAnioMat.getText().isEmpty()){
            try{
                int idMateria = Integer.parseInt(txtCodigoMat.getText());
                String nombreMat = txtNombreMat.getText();
                int anio = Integer.parseInt(txtAnioMat.getText());
                boolean existeMat = Menu.existeMateria(idMateria);
                if(!existeMat){
                    Materia mat = new Materia(idMateria, nombreMat, anio);
                    Menu.agregarMateria(mat);
                    JOptionPane.showMessageDialog(null, "Materia agregada correctamente");
                    txtCodigoMat.setText("");
                    txtNombreMat.setText("");
                    txtAnioMat.setText("");
                    txtCodigoMat.requestFocus();
                }else{
                    JOptionPane.showMessageDialog(null, "Ya existe materia con ese id");
                }
            }catch(NumberFormatException | HeadlessException ex){
                JOptionPane.showMessageDialog(null, "No cumple el formato " + ex.getMessage());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Faltan datos, verificar..");
        }
    }//GEN-LAST:event_btnAceptarMatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarMat;
    private javax.swing.JButton btnSalirMat;
    private javax.swing.JLabel lblAnioMat;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNombreMat;
    private javax.swing.JLabel lblTituloMat;
    private javax.swing.JTextField txtAnioMat;
    private javax.swing.JTextField txtCodigoMat;
    private javax.swing.JTextField txtNombreMat;
    // End of variables declaration//GEN-END:variables
}
