/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.util.ArrayList;
import tp7.Alumno;
import tp7.Materia;

/**
 *
 * @author carlo
 */
public class Menu extends javax.swing.JFrame {
    public static ArrayList<Materia> listaMaterias = new ArrayList<>();
    public static ArrayList <Alumno> listaAlumnos = new ArrayList<>();

    
    public static void agregarMateria(Materia unaMateria){
        listaMaterias.add(unaMateria);
    }

    public static void agregarAlumno(Alumno unAlumno){
        listaAlumnos.add(unAlumno);
    }
    
    public static boolean existeMateria(int codigo){
         boolean existe=false;
         for(int i=0;i<listaMaterias.size();i++){
             if(listaMaterias.get(i).getIdMateria()==codigo){
                 existe=true;
                 break;
             }
         }
         return existe;
     }
    
    public static boolean existeAlumno(int legajo){
        boolean existe=false;
        for (int i=0;i<listaAlumnos.size();i++){
            if (listaAlumnos.get(i).getLegajo()==legajo){
                existe=true;
                break;
            }
        }
        return existe;
    }    
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkPrincipal = new javax.swing.JDesktopPane();
        mnuBarra = new javax.swing.JMenuBar();
        mnuColegio = new javax.swing.JMenu();
        mnuAlumno = new javax.swing.JMenuItem();
        mnuMaterias = new javax.swing.JMenuItem();
        mnuRegistro = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenu();
        mnuSalirSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Colegio");
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(550, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(550, 400));

        dkPrincipal.setPreferredSize(new java.awt.Dimension(550, 350));

        javax.swing.GroupLayout dkPrincipalLayout = new javax.swing.GroupLayout(dkPrincipal);
        dkPrincipal.setLayout(dkPrincipalLayout);
        dkPrincipalLayout.setHorizontalGroup(
            dkPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        dkPrincipalLayout.setVerticalGroup(
            dkPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        mnuColegio.setText("Colegio");

        mnuAlumno.setText("Alumno");
        mnuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAlumnoActionPerformed(evt);
            }
        });
        mnuColegio.add(mnuAlumno);

        mnuMaterias.setText("Materias");
        mnuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMateriasActionPerformed(evt);
            }
        });
        mnuColegio.add(mnuMaterias);

        mnuRegistro.setText("Registro");
        mnuRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistroActionPerformed(evt);
            }
        });
        mnuColegio.add(mnuRegistro);

        mnuBarra.add(mnuColegio);

        mnuSalir.setText("Salir");

        mnuSalirSistema.setText("Salir del Sistema");
        mnuSalirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirSistemaActionPerformed(evt);
            }
        });
        mnuSalir.add(mnuSalirSistema);

        mnuBarra.add(mnuSalir);

        setJMenuBar(mnuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dkPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAlumnoActionPerformed
        // TODO add your handling code here:
        dkPrincipal.removeAll();
        dkPrincipal.repaint();
        FormAlumnos alumnForm = new FormAlumnos();
        alumnForm.setVisible(true);
        dkPrincipal.add(alumnForm);
        dkPrincipal.moveToFront(alumnForm);
    }//GEN-LAST:event_mnuAlumnoActionPerformed

    private void mnuMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMateriasActionPerformed
        // TODO add your handling code here:
        dkPrincipal.removeAll();
        dkPrincipal.repaint();
        FormMaterias matForm = new FormMaterias();
        matForm.setVisible(true);
        dkPrincipal.add(matForm);
        dkPrincipal.moveToFront(matForm);
    }//GEN-LAST:event_mnuMateriasActionPerformed

    private void mnuRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistroActionPerformed
        // TODO add your handling code here:
        dkPrincipal.removeAll();
        dkPrincipal.repaint();
        FormInscripcion insForm = new FormInscripcion();
        insForm.setVisible(true);
        dkPrincipal.add(insForm);
        dkPrincipal.moveToFront(insForm);
    }//GEN-LAST:event_mnuRegistroActionPerformed

    private void mnuSalirSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirSistemaActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirSistemaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dkPrincipal;
    private javax.swing.JMenuItem mnuAlumno;
    private javax.swing.JMenuBar mnuBarra;
    private javax.swing.JMenu mnuColegio;
    private javax.swing.JMenuItem mnuMaterias;
    private javax.swing.JMenuItem mnuRegistro;
    private javax.swing.JMenu mnuSalir;
    private javax.swing.JMenuItem mnuSalirSistema;
    // End of variables declaration//GEN-END:variables
}
